version: '3.7'

services:
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - 3306:3306
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  api:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: maxmovieapi
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true

volumes:
  db-config:
  db-data: